### ISSUE TITLE
検索後に 削除ボタン / detail ボタンが反応しない

### ISSUE THREAD

**Issue by Shunshun94** [Kimi323/kiminofx#1]
検索前は 削除 / detail ボタンが反応するが、
検索後は 削除 / detail ボタンが反応しない。

これは、以下の部分が **その時点で存在している** DOM にだけイベントをバインドしているからです。
https://github.com/Kimi323/fx-logger/blob/2df919e1a97d87446b27081353a61f31f8065aec/views/js/trade.js#L61
そのため、検索後の新たに作られた DOM にはイベントがバインドされません。

この解決方法を3種類提案します。

**1. table がクリックされたら、という形に書き換える**

$('#monthly-result-list') がクリックされた際、クリックされたものに `show-details` クラスがついていたら詳細を表示する function を実行する、という書き方をします。   
手前味噌で恐縮ですが以下が参考になるかと

http://sheeprogramming.iku4.com/javascript/%E4%B8%80%E8%A6%A7%E3%81%AB%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%83%90%E3%82%A4%E3%83%B3%E3%83%89%E3%81%99%E3%82%8B

**2. 要素を新規に作らない**

検索の結果を表示する際に DOM を組み立てなおしています。これで新しく作られた DOM にはイベントがバインドされていないのが原因であることは先述の通りです。

なので、既存の要素のうち、検索結果の対象外の物をすべて display:none; にしてしまう (jQuery を使っているなら show メソッドと hide メソッドが使えますね) という手があります。
これならば、新しい DOM が組み立てられることはないので最初にバインドしたイベントが利用できます。

**3. バインドしなおす**

検索の結果を表示する際に DOM を組み立てなおしています。これで新しく作られた DOM にはイベントがバインドされていないのが原因であることは先述の通りです。

2とは逆のアプローチとして、組み立てなおされた DOM に対して再度イベントをバインドしなおす、という手段もあります。イベントをバインドする部分 (detail ボタンなら以下) を search 結果表示後に再度実行してしまうのです。

https://github.com/Kimi323/fx-logger/blob/2df919e1a97d87446b27081353a61f31f8065aec/views/js/trade.js#L61

---

私なら1 or 3 の手段を取ります。どちらをとるかは割と好みだと思いますが似たような状況下では私は前者を好んで使っています。
件数が大きくなった場合に最初に全件取得・表示するのは少々冗長すぎますので、2のケースは考えにくいかと思いました。

**Comment by Kimi323** [comment]
@Shunshun94 なるほど！！詳しいご説明本当にありがとうございます！！フロントエンド難しいです。。。

**Comment by Kimi323** [comment]
@Shunshun94 遅くなりましたが、こちらの問題解決出来ましたのでクローズさせていただきます。ありがとうございました！
